// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFuY2yupZk3VQFbXL3jollJoaG7HP6XU',
    appId: '1:924916698874:web:716d8274f49c31d9724343',
    messagingSenderId: '924916698874',
    projectId: 'pokedex-kowok',
    authDomain: 'pokedex-kowok.firebaseapp.com',
    storageBucket: 'pokedex-kowok.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YUI9gK451RqocNvO4uUvq5IVFuVkU4w',
    appId: '1:924916698874:android:69fc5f1852a69cb0724343',
    messagingSenderId: '924916698874',
    projectId: 'pokedex-kowok',
    storageBucket: 'pokedex-kowok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-lE4jWR9TyaR4hwz-z9fqJ9u7Wufmzrc',
    appId: '1:924916698874:ios:b232cbf99a49e4f6724343',
    messagingSenderId: '924916698874',
    projectId: 'pokedex-kowok',
    storageBucket: 'pokedex-kowok.appspot.com',
    iosClientId: '924916698874-20g02k74vu0hriv829kh36t150rav0ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexKowok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-lE4jWR9TyaR4hwz-z9fqJ9u7Wufmzrc',
    appId: '1:924916698874:ios:b232cbf99a49e4f6724343',
    messagingSenderId: '924916698874',
    projectId: 'pokedex-kowok',
    storageBucket: 'pokedex-kowok.appspot.com',
    iosClientId: '924916698874-20g02k74vu0hriv829kh36t150rav0ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexKowok',
  );
}
